# Generated by Django 2.0.2 on 2018-02-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_person_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
