# Generated by Django 2.0.2 on 2018-02-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180224_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='Still to come', null=django.db.models.fields.NOT_PROVIDED),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(null=django.db.models.fields.NOT_PROVIDED, on_delete=django.db.models.deletion.CASCADE, to='jobs.Employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_specific_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Still to come 2018-02-24 14:16:47.687589+00:00', max_length=1024),
        ),
    ]
