# Generated by Django 2.0.2 on 2018-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180304_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='TBD', max_length=124),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='Still to come 2018-03-04 13:34:52.521399+00:00', max_length=1024),
        ),
    ]
