# Generated by Django 2.0.2 on 2018-03-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20180304_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='Still to come 2018-03-04 13:38:53.377480+00:00', max_length=1024),
        ),
    ]
